### ISSUE TITLE
dxa.defaults.rich-text-xmlns-remove has no effect

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-model-service#1]
According to the DXA 2.0 Docs (https://docs.sdl.com/LiveContent/content/en-US/SDL%20DXA-v10/GUID-DDB87018-AE37-4624-A033-2483644B4C57), you can get the Model Service to leave the component URI in de xlink:href attribute when resolving the Rich Text field by setting a configuration setting in dxa.properties:

`dxa.defaults.rich-text-xmlns-remove=false`

I have set this property, and restarted the Model Service, but I still don't see the xlink:href in the JSON returned by the Model Service. Scanning the code in this repo, I don't see any reference to this property so I am guessing it has not been implemented?

**Comment by azarakovskiy** [comment]
Hi @willprice76 
There is no any reference to the property because it is mapped to [ConfigService](https://github.com/sdl/dxa-model-service/blob/master/java/dxa-model-service/dxa-model-service-controller/src/main/java/com/sdl/dxa/modelservice/service/ConfigService.java#L65) using [Spring Boot mechanism](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-typesafe-configuration-properties) 

You can find unit tests for this feature [here](https://github.com/sdl/dxa-model-service/blob/master/java/dxa-model-service/dxa-model-service-controller/src/test/java/com/sdl/dxa/tridion/linking/RichTextLinkResolverTest.java#L128)

Are you sure that you set the property in the correct place?
Btw, on Trace level you can check what happens with the property: 
`log.trace("RichTextResolver, resolve = {}, remove = {}, input fragment: '{}'", ...)`

**Comment by willprice76** [comment]
Hi @azarakovskiy - I think the problem is that DXA doesn't use the xlink:href attribute in the rendered JSON, so there is nothing to remove, unless you are using some other JSON format (DD4T?). See https://tridion.stackexchange.com/a/18701/54

**Comment by willprice76** [comment]
In which case the docs are a bit misleading... Or do I have this wrong?

**Comment by azarakovskiy** [comment]
@willprice76 that's correct that DXA doesn't use xlink:href attribute, so we don't even publish it. This feature in Model Service is only used for DD4T content. 

Did the explanation from you solve your issue btw?

I will read the docs whether or they should be re-phrased.

**Comment by rpannekoek** [comment]
Clarified in DXA 2.0 documentation
