### ISSUE TITLE
Anchor tags not closing in model service response with Model service 2.0.3

### ISSUE THREAD

**Issue by qadirkanore** [sdl/dxa-model-service#12]
The link is resolving without a closing tag. suppose i added `<a href="tcm3-7781" title="something">something</a>` then i will see in model service response `<a herf="/en/images/test.jpg" title="something"> something`

**Comment by alebastrov** [comment]
Try not to split "<a href " up into several rows. It should help
{code}
<a href="tcm3-7781" title="something">something</a>
{code}

**Comment by alebastrov** [comment]
@qadirkanore  Please provide details - how link looks like before resolving and after resolving.

Also try to resolve it as single fragment - whole topic text should be a link only like <p><a href="tcm3-7781" title="something">something</a></p>

Maybe something after link prevents it from resolving (for instance many links in one paragraph or smth like this)

**Comment by rpannekoek** [comment]
We have found an issue with hyperlinks in Rich Text which are around embedded Media Items (e.g. images).  In this case, the anchor closing tag does not get lost altogether, but is rendered in the wrong location.
This issue was introduced in the 2.0.3 MS hotfix.

@qadirkanore  Can you confirm that you are observing the problem in such a scenario too?  And can you confirm that the issue does not occur with DXA 2.0.2 MS hotfix  (nor with the original DXA 2.0 MS)?

**Comment by husainZahid** [comment]
@rpannekoek can you please confirm if this defect has been addressed in DXA 2.2 release?

**Comment by rpannekoek** [comment]
Unfortunately, that is not the case (we were already in DXA 2.2 code freeze when this issue was reported), but we are working on hotfixing this for DXA 2.2.  We will update the DXA 2.2 release when it is available.

**Comment by husainZahid** [comment]
Thanks Rick.

**Comment by rpannekoek** [comment]
Internal Issue ID: CRQ-15566

**Comment by majiccode** [comment]
resolved by the latest 2.2.1 hotfix
